[main]
update_offset_wait = 3
debug = true

[kafka]
topic = "roure.avro.subject"
partitions = 3
minbytes = 10000
maxbytes =10000000

[[kafka.broker]]
addr = "localhost:9092"

[avro]
schema = "roure.avro/subject.avsc"

[ledisdb]
addr = "localhost:6380"
password = ""
db = 0