[main]
update_offset_wait = 3
debug = true

[kafka]

[[kafka.topic]]
topic = "roure.avro.subject"
avro_schema = "roure.avro/subject.avsc"
partitions = 3
minbytes = 10000
maxbytes =10000000

[[kafka.topic]]
topic = "roure.avro.comment"
avro_schema = "roure.avro/comment.avsc"
partitions = 3
minbytes = 10000
maxbytes =10000000

[[kafka.topic]]
topic = "roure.avro.activity"
avro_schema = "roure.avro/activity.avsc"
partitions = 2
minbytes = 10000
maxbytes =10000000

[[kafka.broker]]
addr = "localhost:9092"

[ledisdb]
addr = "localhost:6380"
password = ""
db = 0